spring:
  application:
    name: eledger
  datasource:
    url: jdbc:postgresql://localhost:5432/eledger
    username: eledger
    password: eledger

  jpa:
    open-in-view: true
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _aud
            revision_field_name: revision_id
            revision_type_field_name: rev_type
            use_revision_entity_with_native_id: false
            audit_strategy: org.hibernate.envers.strategy.internal.ValidityAuditStrategy
            audit_strategy_validity_end_rev_field_name: revision_end_id

server:
  servlet:
    context-path: /eledger
  port: 8086

logging:
  level:
    root: WARN
    bhutan.eledger: trace
    am.iunetworks.lib.task: trace

task:
  creationSource: Server 1
  tasksScanningInterval: 60

bhutan:
  eledger:
    rma:
      api:
        host: http://uatbfssecure.rma.org.bt
        ar-web-path: /BFSSecure/makePayment
        as-check-status-path: /BFSSecure/checkStatus
        ar-mobile-path: /BFSSecure/nvpapi
        version: 5.0
      sign:
        ks-location: classpath:keystores/rma/bu_rma_ks.p12
        ks-password: yPDPvmMarz9Dt64M
        ks-type: PKCS12
        algorithm: SHA1withRSA
        key-password: yPDPvmMarz9Dt64M
        key-alias: bu_rma_ks_alias
      beneficiary:
        id: BE10000169
        bank-code: "01"
      task:
        retry-count-until-fail: 3
    fms:
      uri: http://10.11.1.13
    glaccount:
      search:
        sort-property: code
    schedule:
      accounting:
        calculation:
          cron: "@midnight" #0 0 0 * * *

